name: skip-workflow-e2e-test

on:
  workflow_dispatch:
    inputs:
      sha:
        description: SHA of commit to test
        required: true
jobs:
  skip-workflow-test-job:
    runs-on: ubuntu-latest
    outputs:
      skip-job: ${{ steps.skip-workflow.outputs.match-found }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: test-action
        id: skip-workflow
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          phrase: '[skip-workflow]'
          pr-id: 6

  test-action:
    needs: skip-workflow-test-job

    if: ${{ !needs.skip-workflow-test-job.outputs.skip-job }}
    runs-on: ubuntu-latest
    name: test-job-1
    steps:
      - name: fail-check
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/saulmaldonado/skip-workflow/check-runs \
            -d '{"name":"skip-workflow-e2e-test","head_sha": "${{ github.event.inputs.sha }}", "conclusion": "failure"}'

      - name: this-command-should-not-run
        run: exit 1

  test-action-2:
    needs: skip-workflow-test-job

    if: ${{ !needs.skip-workflow-test-job.outputs.skip-job }}
    runs-on: ubuntu-latest
    name: test-job-2
    steps:
      - name: fail-check
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/saulmaldonado/skip-workflow/check-runs \
            -d '{"name":"skip-workflow-e2e-test","head_sha": "${{ github.event.inputs.sha }}", "conclusion": "failure"}'
      - name: this-command-should-not-run-2
        run: exit 1

  pass-check:
    needs: skip-workflow-test-job

    if: ${{ needs.skip-workflow-test-job.outputs.skip-job }}

    runs-on: ubuntu-latest
    name: pass-check
    steps:
      - name: pass-check
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/saulmaldonado/skip-workflow/check-runs \
            -d '{"name":"skip-workflow-e2e-test","head_sha": "${{ github.event.inputs.sha }}", "conclusion": "success"}'
